export const PIPELINE_STEPS = [
  {
    name: 'gtm-analytics-audit',
    label: 'Audit',
    route: '/audit',
    description: 'Scan codebase for trackable elements',
    shortDescription: 'Find what can be tracked',
    what: [
      'Scans all component files for buttons, links, forms, and interactive elements',
      'Identifies existing tracking code and measures current coverage',
      'Categorizes elements by type: CTAs, navigation, forms, media, outbound links',
    ],
    inputs: 'Your codebase at the configured project path',
    outputs: 'Coverage report with gap analysis and prioritized recommendations',
    estimatedTime: '2–5 min',
    modifiesFiles: false,
  },
  {
    name: 'gtm-dom-standardization',
    label: 'Prepare Elements',
    route: '/dom',
    description: 'Add analytics-ready IDs and classes to elements',
    shortDescription: 'Clean up element identifiers',
    what: [
      'Adds consistent id and class attributes to unidentified interactive elements',
      'Applies naming convention: id="cta_hero_get_started", class="js-track js-cta"',
      'Proposes file-by-file diffs for your review before applying anything',
    ],
    inputs: 'Audit report from Step 1 identifying elements that need standardization',
    outputs: 'Modified source files with analytics-ready element identifiers',
    estimatedTime: '3–8 min',
    modifiesFiles: true,
  },
  {
    name: 'gtm-strategy',
    label: 'Strategy',
    route: '/strategy',
    description: 'Plan events and tracking priorities',
    shortDescription: 'Define what to track and why',
    what: [
      'Defines GA4 event names, parameters, and priority tiers (P0/P1/P2) for each element',
      'Maps business goals to specific tracking events with expected value',
      'Produces a tracking plan that drives the Implementation step',
    ],
    inputs: 'Audit report and standardized DOM from Steps 1–2',
    outputs: 'Tracking plan JSON with event definitions and business justifications',
    estimatedTime: '3–6 min',
    modifiesFiles: false,
  },
  {
    name: 'gtm-implementation',
    label: 'Implementation',
    route: '/implementation',
    description: 'Add dataLayer events and create GTM configs',
    shortDescription: 'Write the actual tracking code',
    what: [
      'Adds dataLayer.push() calls to your source files for each tracked element',
      'Creates GTM tags, triggers, and variables via the API',
      'Follows the tracking plan from Step 3 exactly',
    ],
    inputs: 'Tracking plan from Step 3 and GTM connection from Step 4',
    outputs: 'Modified source files with dataLayer events + GTM container configuration',
    estimatedTime: '5–15 min',
    modifiesFiles: true,
  },
  {
    name: 'gtm-testing',
    label: 'Testing',
    route: '/testing',
    description: 'Validate tracking across 3 tiers',
    shortDescription: 'Verify everything fires correctly',
    what: [
      'Tier 1: Static analysis — confirms dataLayer calls match the tracking plan',
      'Tier 2: GTM preview mode — validates tags fire on the right triggers',
      'Tier 3: GA4 DebugView — confirms events reach Google Analytics',
    ],
    inputs: 'Implemented tracking from Step 5',
    outputs: 'Test report with pass/fail per event and any detected issues',
    estimatedTime: '3–8 min',
    modifiesFiles: false,
  },
  {
    name: 'gtm-reporting',
    label: 'Reporting',
    route: '/reporting',
    description: 'Generate documentation and summaries',
    shortDescription: 'Export your tracking documentation',
    what: [
      'Generates a human-readable tracking implementation summary',
      'Produces a data dictionary of all events and parameters',
      'Creates a handoff document for stakeholders and future developers',
    ],
    inputs: 'All previous step outputs',
    outputs: 'Markdown report, data dictionary, and stakeholder summary',
    estimatedTime: '2–4 min',
    modifiesFiles: false,
  },
] as const

export type SkillName = typeof PIPELINE_STEPS[number]['name']

export const API_BASE = '/api'
